name: "if-conditional-pipeline"
description: "Pipeline di esempio per testare l'IfStep con logica condizionale e branching"
stages:
  # Stage di delay che simula elaborazione
  - id: "process"
    step_type: "delay"
    step_config:
      ms: 100

  # Stage if che valuta una condizione
  # La condizione può essere una semplice espressione booleana o
  # un'espressione che usa i dati degli step precedenti (es. ctx.process)
  - id: "check"
    step_type: "if"
    step_config:
      condition: "$js: 1 === 2"  # Condizione casuale per test
    dependencies:
      - "process"

  # Stage eseguito SOLO quando la condizione è TRUE
  # Usa la sintassi "step_id:branch" per specificare il filtro
  - id: "on_true"
    step_type: "delay"
    step_config:
      ms: 50
    dependencies:
      - "check:true"  # Dipende solo dal ramo "true" dello step check

  # Stage eseguito SOLO quando la condizione è FALSE
  - id: "on_false"
    step_type: "delay"
    step_config:
      ms: 50
    dependencies:
      - "check:false"  # Dipende solo dal ramo "false" dello step check

  # Stage che dipende da ENTRAMBI i rami (viene eseguito sempre)
  # Se vuoi uno stage che si attiva con qualsiasi output dello step if,
  # usa semplicemente il nome dello step senza suffisso
  - id: "always"
    step_type: "delay"
    step_config:
      ms: 25
    dependencies:
      - "check"  # Senza suffisso: accetta qualsiasi output (true o false)
